export const CHARACTERS_FETCH_REQUESTED = 'CHARACTERS_FETCH_REQUESTED';
export const CHARACTERS_FETCH_SUCCEEDED = 'CHARACTERS_FETCH_SUCCEEDED';
export const CHARACTERS_FETCH_FAILED = 'CHARACTERS_FETCH_FAILED';
export const MORE_CHARACTERS_FETCH_REQUESTED = 'MORE_CHARACTERS_FETCH_REQUESTED';
export const MORE_CHARACTERS_FETCH_SUCCEEDED = 'MORE_CHARACTERS_FETCH_SUCCEEDED';
export const MORE_CHARACTERS_FETCH_FAILED = 'MORE_CHARACTERS_FETCH_FAILED';
