export const CHARACTERS_FETCH_SUCCEEDED = 'CHARACTERS_FETCH_SUCCEEDED';
export const CHARACTERS_FETCH_FAILED = 'CHARACTERS_FETCH_FAILED';
export const CHARACTERS_FETCH_REQUESTED = 'CHARACTERS_FETCH_REQUESTED';
